# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_auto_20161102_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo_programa',
            field=models.ManyToManyField(to='programas.Tipo_Programa'),
        ),
    ]
