# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0005_auto_20161102_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='ampliacion_cobertura',
            field=models.CharField(choices=[('s', 'S'), ('n', 'N')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_contratistas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_contratistas_externos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_inst_empresa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_monitores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='total_horas',
            field=models.IntegerField(),
        ),
    ]
